In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from category_encoders import TargetEncoder

In [ ]:
df = pd.read_csv('C:\\Users\\Admin\\OneDrive\\Desktop\\data science\\ML\\SUPERVISED LEARNING\\Dataset\\student_performance.csv')

In [3]:
X = df.drop(columns='Performance Index')
y = df['Performance Index']

In [4]:
xtrain,xtest, ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

## LabelEncoder

In [5]:
# encoder = LabelEncoder()

# xtrain['Extracurricular Activities'] = encoder.fit_transform(xtrain['Extracurricular Activities'])

# xtest['Extracurricular Activities'] = encoder.transform(xtest['Extracurricular Activities'])

In [6]:
# encoder.transform(['OK']) # tranform the unseen label then it raises the KeyError

## OneHotEncoder

In [7]:
# encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
# # by default handle unknown is error 
# # giving to 'ignore' it ignore the eroor insted of giving error it fills with the  0

# # encoder.fit_transform(xtrain['Extracurricular Activities'])
# # Expected a 2-dimensional container but got <class 'pandas.Series'> instead.

# xtrain[['Extracurricular Activities_No','Extracurricular Activities_Yes']]= encoder.fit_transform(xtrain[['Extracurricular Activities']])

In [8]:
# xtrain.drop(columns=['Extracurricular Activities'],inplace=True)

In [9]:
# xtest[['Extracurricular Activities_No','Extracurricular Activities_Yes']] = encoder.transform(xtest[['Extracurricular Activities']])
# xtest.drop(columns=['Extracurricular Activities'],inplace=True)

In [10]:
# encoder.transform([['OK']])
# ValueError: Found unknown categories ['OK'] in column 0 during transform

In [11]:
# encoder.transform([['OK'],['No'],['Yes']])
# # we use handle_unknown='ignore' so here unseen label it fill with the 0 both columns

## OrdinalEncoder

In [12]:
# encoder = OrdinalEncoder(categories=[['Yes','No']],handle_unknown='use_encoded_value',unknown_value=-1)

# xtrain['Extracurricular Activities'] = encoder.fit_transform(xtrain[['Extracurricular Activities']])

In [13]:
# xtest['Extracurricular Activities'] = encoder.transform(xtest[['Extracurricular Activities']])

In [14]:
# encoder.transform([['Yes'],['No'],['ok']])

## TargetEncoder

In [15]:
encoder = TargetEncoder()

encoder.fit_transform(xtrain['Extracurricular Activities'],ytrain)

      Extracurricular Activities
9254                   54.956468
1561                   55.674248
1670                   54.956468
6087                   54.956468
6669                   54.956468
...                          ...
5734                   55.674248
5191                   54.956468
5390                   54.956468
860                    54.956468
7270                   54.956468

[8000 rows x 1 columns]

In [16]:
encoder.transform(xtest['Extracurricular Activities'])

      Extracurricular Activities
6252                   54.956468
4684                   55.674248
1731                   55.674248
4742                   55.674248
4521                   54.956468
...                          ...
6412                   54.956468
8285                   54.956468
7853                   55.674248
1095                   54.956468
6929                   54.956468

[2000 rows x 1 columns]

In [22]:
X=pd.DataFrame({
    'Extracurricular Activities':['Yes','No','Ok','yes']
})
encoder.transform(X)

   Extracurricular Activities
0                   55.674248
1                   54.956468
2                   55.311500
3                   55.311500