In [1]:
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [ ]:
df = pd.read_csv('C:\\Users\\Admin\\OneDrive\\Desktop\\data science\\ML\\SUPERVISED LEARNING\\Dataset\\loan_approval_dataset.csv')
X = df.drop(columns='Loan_Approved')
y = df['Loan_Approved']
df

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No
...,...,...,...,...,...,...,...,...,...
995,22,49241,500,41020,24 months,Self-Employed,Owned,No,Yes
996,40,116214,423,12415,48 months,Self-Employed,Owned,No,Yes
997,27,64569,300,28155,36 months,Self-Employed,Rented,Yes,Yes
998,61,31745,490,48884,12 months,Self-Employed,Mortgage,No,Yes
999,19,46029,815,21964,24 months,Employed,Mortgage,Yes,No

In [3]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [4]:
num_cols = X.select_dtypes(include='number').columns
obj_cols = X.select_dtypes(exclude='number').columns

In [5]:
preprocessing = ColumnTransformer(
    transformers=[
        ('scaling',StandardScaler(),num_cols),
        ('encoder',OneHotEncoder(),obj_cols)
    ],
    remainder='passthrough'
)
values = preprocessing.fit_transform(xtrain)

In [6]:
col_name = preprocessing.get_feature_names_out()

In [7]:
xtrain = pd.DataFrame(data=values,columns=col_name)
xtrain

,scaling__Age,scaling__Salary,scaling__Credit_Score,scaling__Loan_Amount,encoder__Loan_Term_12 months,encoder__Loan_Term_24 months,encoder__Loan_Term_36 months,encoder__Loan_Term_48 months,encoder__Employment_Status_Employed,encoder__Employment_Status_Self-Employed,encoder__Employment_Status_Unemployed,encoder__Residence_Type_Mortgage,encoder__Residence_Type_Owned,encoder__Residence_Type_Rented,encoder__Previous_Default_No,encoder__Previous_Default_Yes
0,0.217341,0.001268,-0.440664,-0.790774,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,-0.222472,0.049597,-0.555050,-1.281818,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.290643,-0.930762,1.179804,0.940788,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.437247,-0.261695,1.478479,1.030343,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.363945,0.409350,-0.459728,0.360422,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.803758,0.867453,0.715905,0.336618,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
796,-1.102097,1.308093,-1.196882,-0.371685,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
797,1.683383,1.291202,0.677777,-1.447282,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
798,-1.102097,-0.976906,1.681831,1.425861,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
799,-0.955493,-0.156500,-1.717974,-1.219400,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [8]:
xtest = preprocessing.transform(xtest)

In [9]:
xtrain

,scaling__Age,scaling__Salary,scaling__Credit_Score,scaling__Loan_Amount,encoder__Loan_Term_12 months,encoder__Loan_Term_24 months,encoder__Loan_Term_36 months,encoder__Loan_Term_48 months,encoder__Employment_Status_Employed,encoder__Employment_Status_Self-Employed,encoder__Employment_Status_Unemployed,encoder__Residence_Type_Mortgage,encoder__Residence_Type_Owned,encoder__Residence_Type_Rented,encoder__Previous_Default_No,encoder__Previous_Default_Yes
0,0.217341,0.001268,-0.440664,-0.790774,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,-0.222472,0.049597,-0.555050,-1.281818,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.290643,-0.930762,1.179804,0.940788,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.437247,-0.261695,1.478479,1.030343,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.363945,0.409350,-0.459728,0.360422,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.803758,0.867453,0.715905,0.336618,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
796,-1.102097,1.308093,-1.196882,-0.371685,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
797,1.683383,1.291202,0.677777,-1.447282,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
798,-1.102097,-0.976906,1.681831,1.425861,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
799,-0.955493,-0.156500,-1.717974,-1.219400,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0